version: '3.7'

services:
  app:
    container_name: 'app'
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3005:3005
    stdin_open: true
    environment:
      - PORT=3005
    command: npm start

volumes:
  node_modules: